"""New Initial Migration with Prices updated

Revision ID: 7327fc209410
Revises: 91c43d18be44
Create Date: 2022-09-30 18:30:05.434849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7327fc209410'
down_revision = '91c43d18be44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('inventory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['name'], ['inventory_name.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    # ### end Alembic commands ###
